### ISSUE TITLE
Is it useful to add a compatibility doc?

### ISSUE THREAD

**Issue by jonmach** [leozide/pocketbg#1]
Hi,

I cannot compile pocketbg on the (currently) latest version of XCode (9.4.1) as it generates numerous warnings and then a semantic issue on line 3216 of bgView.mm.

anim.delegate = self;  Error is "Assigning to 'id<CAAnimationDelegate> _Nullable' from incompatible type 'bgView *' "

As this code gets relatively older, is it possible to add a new document outlining expected problems and approaches to resolving them?

I will eventually resolve this, but it may be specific to my XCode and therefore a pull-request and subsequent patch may not be useful to everyone.

Just a thought

**Comment by leozide** [comment]
I haven't updated my Xcode in a while, I only do it when I need to recompile PocketBG and if my iOS is too new. I don't use my Mac much these days, next time I boot it I'll check the version and add a note and if I have time I'll update my Mac and fix the compile errors.

**Comment by jonmach** [comment]
Thanks - appreciated

**Comment by leozide** [comment]
I've updated the code and added a note to the readme.
